language: python
python:
  - "2.7git
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

services:
  - postgresql

before_script:
  - psql -c 'create database farooq;' -U postgres
  - psql -c 'create database apitest;' -U postgres
  
# command to run tests
script:
  - python3 -m pytest --cov=app tests/

after_success:
- coveralls